// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'transaction_info.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$TransactionInfoImpl _$$TransactionInfoImplFromJson(
        Map<String, dynamic> json) =>
    _$TransactionInfoImpl(
      reasonCode: (json['ReasonCode'] as num).toInt(),
      publicId: json['PublicId'] as String?,
      terminalUrl: json['TerminalUrl'] as String?,
      transactionId: (json['TransactionId'] as num?)?.toInt(),
      amount: (json['Amount'] as num?)?.toInt(),
      currency: json['Currency'] as String?,
      currencyCode: (json['CurrencyCode'] as num?)?.toInt(),
      paymentAmount: (json['PaymentAmount'] as num?)?.toInt(),
      paymentCurrency: json['PaymentCurrency'] as String?,
      paymentCurrencyCode: (json['PaymentCurrencyCode'] as num?)?.toInt(),
      invoiceId: json['InvoiceId'] as String?,
      accountId: json['AccountId'] as String?,
      email: json['Email'] as String?,
      description: json['Description'] as String?,
      jsonData: json['JsonData'] as Map<String, dynamic>?,
      createdDate: json['CreatedDate'] as String?,
      payoutDate: json['PayoutDate'] as String?,
      payoutDateIso: json['PayoutDateIso'] as String?,
      payoutAmount: (json['PayoutAmount'] as num?)?.toDouble(),
      createdDateIso: json['CreatedDateIso'] as String?,
      authDate: json['AuthDate'] as String?,
      authDateIso: json['AuthDateIso'] as String?,
      confirmDate: json['ConfirmDate'] as String?,
      confirmDateIso: json['ConfirmDateIso'] as String?,
      authCode: json['AuthCode'] as String?,
      testMode: json['TestMode'] as bool?,
      rrn: json['Rrn'] as String?,
      originalTransactionId: (json['OriginalTransactionId'] as num?)?.toInt(),
      fallBackScenarioDeclinedTransactionId:
          (json['FallBackScenarioDeclinedTransactionId'] as num?)?.toInt(),
      ipAddress: json['IpAddress'] as String?,
      ipCountry: json['IpCountry'] as String?,
      ipCity: json['IpCity'] as String?,
      ipRegion: json['IpRegion'] as String?,
      ipDistrict: json['IpDistrict'] as String?,
      ipLatitude: (json['IpLatitude'] as num?)?.toDouble(),
      ipLongitude: (json['IpLongitude'] as num?)?.toDouble(),
      cardFirstSix: json['CardFirstSix'] as String?,
      cardLastFour: json['CardLastFour'] as String?,
      cardExpDate: json['CardExpDate'] as String?,
      cardType: json['CardType'] as String?,
      cardProduct: json['CardProduct'] as String?,
      cardCategory: json['CardCategory'] as String?,
      escrowAccumulationId: json['EscrowAccumulationId'] as String?,
      issuerBankCountry: json['IssuerBankCountry'] as String?,
      issuer: json['Issuer'] as String?,
      cardTypeCode: (json['CardTypeCode'] as num?)?.toInt(),
      status: json['Status'] as String?,
      statusCode: (json['StatusCode'] as num?)?.toInt(),
      cultureName: json['CultureName'] as String?,
      reason: json['Reason'] as String?,
      cardHolderMessage: json['CardHolderMessage'] as String?,
      type: (json['Type'] as num?)?.toInt(),
      refunded: json['Refunded'] as bool?,
      name: json['Name'] as String?,
      token: json['Token'] as String?,
      subscriptionId: json['SubscriptionId'] as String?,
      gatewayName: json['GatewayName'] as String?,
      applePay: json['ApplePay'] as bool?,
      androidPay: json['AndroidPay'] as bool?,
      walletType: json['WalletType'] as String?,
      totalFee: (json['TotalFee'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$$TransactionInfoImplToJson(
        _$TransactionInfoImpl instance) =>
    <String, dynamic>{
      'ReasonCode': instance.reasonCode,
      'PublicId': instance.publicId,
      'TerminalUrl': instance.terminalUrl,
      'TransactionId': instance.transactionId,
      'Amount': instance.amount,
      'Currency': instance.currency,
      'CurrencyCode': instance.currencyCode,
      'PaymentAmount': instance.paymentAmount,
      'PaymentCurrency': instance.paymentCurrency,
      'PaymentCurrencyCode': instance.paymentCurrencyCode,
      'InvoiceId': instance.invoiceId,
      'AccountId': instance.accountId,
      'Email': instance.email,
      'Description': instance.description,
      'JsonData': instance.jsonData,
      'CreatedDate': instance.createdDate,
      'PayoutDate': instance.payoutDate,
      'PayoutDateIso': instance.payoutDateIso,
      'PayoutAmount': instance.payoutAmount,
      'CreatedDateIso': instance.createdDateIso,
      'AuthDate': instance.authDate,
      'AuthDateIso': instance.authDateIso,
      'ConfirmDate': instance.confirmDate,
      'ConfirmDateIso': instance.confirmDateIso,
      'AuthCode': instance.authCode,
      'TestMode': instance.testMode,
      'Rrn': instance.rrn,
      'OriginalTransactionId': instance.originalTransactionId,
      'FallBackScenarioDeclinedTransactionId':
          instance.fallBackScenarioDeclinedTransactionId,
      'IpAddress': instance.ipAddress,
      'IpCountry': instance.ipCountry,
      'IpCity': instance.ipCity,
      'IpRegion': instance.ipRegion,
      'IpDistrict': instance.ipDistrict,
      'IpLatitude': instance.ipLatitude,
      'IpLongitude': instance.ipLongitude,
      'CardFirstSix': instance.cardFirstSix,
      'CardLastFour': instance.cardLastFour,
      'CardExpDate': instance.cardExpDate,
      'CardType': instance.cardType,
      'CardProduct': instance.cardProduct,
      'CardCategory': instance.cardCategory,
      'EscrowAccumulationId': instance.escrowAccumulationId,
      'IssuerBankCountry': instance.issuerBankCountry,
      'Issuer': instance.issuer,
      'CardTypeCode': instance.cardTypeCode,
      'Status': instance.status,
      'StatusCode': instance.statusCode,
      'CultureName': instance.cultureName,
      'Reason': instance.reason,
      'CardHolderMessage': instance.cardHolderMessage,
      'Type': instance.type,
      'Refunded': instance.refunded,
      'Name': instance.name,
      'Token': instance.token,
      'SubscriptionId': instance.subscriptionId,
      'GatewayName': instance.gatewayName,
      'ApplePay': instance.applePay,
      'AndroidPay': instance.androidPay,
      'WalletType': instance.walletType,
      'TotalFee': instance.totalFee,
    };
